### PR TITLE
Bump ndarray to 0.16

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by kylebarron** [comment]
I'm not sure what's different so as to no longer be able to build GDAL on CI

**Comment by nmandery** [comment]
The `gdal` crate itself depends on `ndarray` 0.15. PR is in https://github.com/georust/gdal/pull/569.

This crate requires gdal only for one example, we could also just comment out this example and the gdal dev-dependency.

**Comment by kylebarron** [comment]
Ah I see. It seemed that numpy 0.22 forced a ndarray 0.15 upgrade. If you think gdal will upgrade to 0.16 soon anyways, then maybe we just comment out the example for now?

**Comment by nmandery** [comment]
Just comment it out - it is just a non-essential example.

**Comment by kylebarron** [comment]
It looks like crates.io allows git tags for dev dependencies (it just [ignores them](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#the-role-of-the-version-key)), so I'm going to try pinning the latest main of gdal here. Can you run the CI? @nmandery

**Comment by nmandery** [comment]
Thank you for this PR. I already pushed the this as version `0.9.0` to crates.io.

**Pull request merged**
